<?php
/**
 * Created by PhpStorm.
 * User: Soso
 * Date: 11/6/2018
 * Time: 3:47 PM
 */

namespace App\Controllers;


use App\Inc\DataService;
use App\Models\CategoryModel;

class FrontController
{
    public function register() {


        //add_action( 'wp_ajax_nopriv_lux_vendor_get_materials', [$this,'getJsonMaterials'] );
        add_action( 'wp_ajax_lux_vendor_get_materials', [$this,'getJsonMaterials'] );
        add_action( 'wp_ajax_nopriv_lux_vendor_get_materials', [$this,'getJsonMaterials'] );
        add_action( 'wp_ajax_lux_vendor_clpe', [$this,'calculatePrice'] );

        add_action( 'wp_ajax_md_support_save',[$this,'md_support_save'] );
        add_action( 'wp_ajax_nopriv_md_support_save',[$this,'md_support_save'] );
    }

    function calculatePrice()
    {

        // validate nonce
        if ( !wp_verify_nonce( $_REQUEST['nonce'], "my_user_vote_nonce")) {
            exit("No naughty business please");
        }
        echo json_encode(['p'=>5000]);

        die();exit();
        //get

    }

    function getJsonMaterials()
    {

        // validate nonce
        if ( !wp_verify_nonce( $_REQUEST['nonce'], "my_user_vote_nonce")) {
            exit("No naughty business please");
        }

        $materials = CategoryModel::show($_POST['category_id']);
        echo json_encode($materials);

        die();
        //get

    }

    function dashboard()
    {
        // Double check user capabilities
       // if ( !current_user_can('manage_options') ) {
         //   return;
       // }


        _includes('front/dashboard.php',[

            'conditions'=>DataService::wooCommerceCondition(),
        ]);
    }

    public function md_support_save(){
       //  print_r($_POST);print_r($_FILES);
         $data = [];

        if (!function_exists('wp_handle_upload')) {
            require_once(ABSPATH . 'wp-admin/includes/file.php');
        }
        // echo $_FILES["upload"]["name"];
        $uploadedfile = $_FILES['file'];
        $upload_overrides = array('test_form' => false);




            ////// validate the file size ///////
        /*$tmpName = $uploadedfile['tmp_name'];
        list($width, $height, $type, $attr) = @getimagesize($tmpName);
        if ($width != 500 || $height != 500) {
            $error .= "Image is to small<br />";
            unlink($uploadedfile['tmp_name']);
        }*/

        // Get the type of the uploaded file. This is returned as "type/extension"
        $arr_file_type = wp_check_filetype(basename($uploadedfile['name']));
        $uploaded_file_type = $arr_file_type['type'];

        // Set an array containing a list of acceptable formats
        $allowed_file_types = array('image/jpg','image/jpeg','image/gif','image/png');

        // If the uploaded file is the right format
        if (in_array($uploaded_file_type, $allowed_file_types)) {
        } else { // wrong file type
            $data['error'] .= "Please upload a JPG, GIF, or PNG file<br />";
        }


        $movefile = wp_handle_upload($uploadedfile, $upload_overrides);


        if ($movefile && !isset($movefile['error'])) {
            $data['msg']    = "File Upload Successfully";
            $data['status'] = 'success';
            $data['url']    = $movefile['url'];
        } else {
            /**
             * Error generated by _wp_handle_upload()
             * @see _wp_handle_upload() in wp-admin/includes/file.php
             */
            $data['msg'] = $movefile['error'];
            $data['status'] = 'error';
            $data['url']    = '';
        }

        echo json_encode($data);
        die();
    }
}